/* Google Closure Compiler : http://closure-compiler.appspot.com/home */
/* cdn upload path : http://cdn-exchange.toastoven.net/cdn/adx/js/rta_all.js */

if("object"!==typeof JSON){var JSON=JSON||{};JSON.stringify=JSON.stringify||function(a){var h=typeof a;if("object"!=h||null===a)return"string"==h&&(a='"'+a+'"'),String(a);var e,g,k=[],f=a&&a.constructor==Array;for(e in a)g=a[e],h=typeof g,"string"==h?g='"'+g+'"':"object"==h&&null!==g&&(g=JSON.stringify(g)),k.push((f?"":'"'+e+'":')+String(g));return(f?"[":"{")+String(k)+(f?"]":"}")};JSON.parse=JSON.parse||function(a){""===a&&(a='""');eval("var p="+a+";");return p}}var ttx_criteo_result="";
(function(){function a(c,b,a){var d=document.createElement("script");d.type="text/javascript";d.src=c;d.readyState?d.onreadystatechange=function(){if("loaded"==d.readyState||"complete"==d.readyState)d.onreadystatechange=null,b(a)}:d.onload=function(){b(a)};0<document.getElementsByTagName("head").length?document.getElementsByTagName("head")[0].appendChild(d):0<document.getElementsByTagName("body").length&&document.getElementsByTagName("body")[0].appendChild(d)}function h(c){if(c==e.criteo.name){e.criteo.ok=
"y";for(var b=0;b<l.length;b++)q=f[l[b].area_code].criteo="1"}if("off"==e.criteo.status||"y"==e.criteo.ok||"timeout"==c){clearTimeout(t);c=new Date;c.setTime(c.getTime()+e.cookie_expire);b=JSON.stringify(f);try{var a=JSON.parse(u(ttx_total_cookie_name))||{};for(area_code_key in a)0==f.hasOwnProperty(area_code_key)&&(f[area_code_key]=a[area_code_key],f[area_code_key].criteo=q);500>JSON.stringify(f).length&&(b=JSON.stringify(f))}catch(d){}ttx_total_result+=b;eval("try { document.cookie='"+ttx_total_cookie_name+
"="+b+"; path=/; expires=Thu, 01 Jan 1970 00:00:01 GMT; domain="+document.domain.split(".").slice(-3).join(".")+";' } catch (ee) { } ");eval("document.cookie='"+ttx_total_cookie_name+"="+b+"; path=/; expires="+c.toUTCString()+"; domain="+document.domain.split(".").slice(-2).join(".")+";'");eval("try { if (document.cookie.search('"+ttx_total_cookie_name+"')===-1) { document.cookie='"+ttx_total_cookie_name+"="+b+"; path=/; expires="+c.toUTCString()+"; domain="+document.domain.split(".").slice(-3).join(".")+
";' } } catch (ee) { } ");ttx_cb_func()}}for(var e={cookie_expire:2592E6,timeout:1E3,criteo:{name:"criteo",ok:"n",cookie_name:"ttx_bnrs_e",var_name:"ttx_criteo_result",status:"on"}},g=[],k=[],f={},l=ttx_area_info.slice(),m=0;m<l.length;m++){var n=l[m].area_code;g.push(n);"pag"in l[m]?k.push(encodeURIComponent(l[m].pag)):k.push("");f[n]={};f[n].criteo="0"}var q="0";g.join("|");k.join("|");if("undefined"==typeof ttx_domain||"null"==typeof ttx_domain)ttx_domain="";if("undefined"==typeof ttx_page_url||
"null"==typeof ttx_page_url)ttx_page_url=document.URL;if("undefined"==typeof ttx_refer||"null"==typeof ttx_refer)ttx_refer=document.referrer;var u=function(c){c+="=";for(var b=document.cookie.split(";"),a=0;a<b.length;a++){for(var d=b[a];" "==d.charAt(0);)d=d.substring(1);if(0==d.indexOf(c))return d.substring(c.length,d.length)}return""},t=setTimeout(function(){h("timeout")},e.timeout);if("on"==e.criteo.status){var r=e.criteo.cookie_name,v=e.criteo.var_name;(function(a){var b,e,d,f=document.cookie.split(";");
for(b=0;b<f.length;b++)if(e=f[b].substr(0,f[b].indexOf("=")),d=f[b].substr(f[b].indexOf("=")+1),e=e.replace(/^\s+|\s+$/g,""),e==a)return unescape(d);return""})(r);var w=Math.floor(99999999999*Math.random());(function(){var c=location.protocol+"//rtax.criteo.com/delivery/rta/rta.js?netId="+escape("4158"),c=c+("&cookieName="+escape(r)),c=c+("&rnd="+w),c=c+("&varName="+escape(v));a(c,h,e.criteo.name)})()}})();
